---

- name: Test DataPower domain module (create)
  connection: local
  hosts: localhost

  tasks:

  - name: Include connection data
    include_vars:
        file: idg-connection.yml
        name: remote_idg

  - name: Create multiple domain
    idg_domain:
        name: "test-{{ item }}"
        idg_connection: "{{ remote_idg }}"
        user_summary: "Dominio {{ item }} de {{ total }}"
        state: present
    with_sequence: start=1 end={{ total | int }}
    register: create_domain_out
    vars:
        total: 20

  - name: Dump multiple create output
    debug:
        var: create_domain_out

...
