---

- name: Test DataPower domain module (remove)
  connection: local
  hosts: localhost

  tasks:

  - name: Include connection data
    include_vars:
        file: idg-connection.yml
        name: remote_idg

  - name: Remove domain
    idg_domain:
        name: "{{ domain_name }}"
        idg_connection: "{{ remote_idg }}"
        state: absent
    register: remove_domain_out

  - name: Dump remove output
    debug:
        var: remove_domain_out

...
