---

- name: Test DataPower domain module (reset)
  connection: local
  hosts: localhost

  tasks:

  - name: Include connection data
    include_vars:
        file: idg-connection.yml
        name: remote_idg

  - name: Reset domain
    idg_domain:
        name: "{{ domain_name }}"
        idg_connection: "{{ remote_idg }}"
        state: reseted
    register: reset_domain_out

  - name: Dump reset output
    debug:
        var: reset_domain_out

...
