---

- name: Test DataPower domain module (unquiesce)
  connection: local
  hosts: localhost

  tasks:

  - name: Include connection data
    include_vars:
        file: idg-connection.yml
        name: remote_idg

  - name: Unquiesce domain
    idg_domain:
        name: "{{ domain_name }}"
        idg_connection: "{{ remote_idg }}"
        state: unquiesced
    register: unquiesce_domain_out

  - name: Dump unquiesce output
    debug:
        var: unquiesce_domain_out

...
