---

- name: Test DataPower domain module checkpoint (remove)
  connection: local
  hosts: localhost

  tasks:

  - name: Include connection data
    include_vars:
        file: idg-connection.yml
        name: remote_idg

  - name: Remove checkpoint
    idg_domain_chkpoint:
        name: "{{ chkpoint_name }}"
        domain: "{{ domain_name }}"
        idg_connection: "{{ remote_idg }}"
        state: absent
    register: rm_chk_out

  - name: Dump remove checkpoint
    debug:
        var: rm_chk_out

...
